version: '3'

services:
  api:
    build:
      context: ./
    depends_on:
      - db
    ports:
      - 8080:8080
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./.docker/database:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

volumes:
  postgres_data:
