version: '3'

services:
  api:
    build:
      context: ./
    depends_on:
      - db
    ports:
      - 8080:8080
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres_data:
